name: Laravel CI/CD

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run Laravel Validation
        run: php artisan --version

      - name: Docker Build
        run: docker build -t praytimenow .

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Push to Azure Container Registry
        run: |
          docker tag praytimenow myregistry.azurecr.io/praytimenow
          docker push myregistry.azurecr.io/praytimenow

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "PrayTimeNowApp"
          images: "myregistry.azurecr.io/praytimenow"
